# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlinePluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_headlinepluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.CharField(default='Text der Überschrift', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ParralaxPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_parralaxpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('bild', models.ImageField(upload_to='parralax-background-images/')),
                ('text', models.CharField(default='Text der Überschrift', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
