# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parralaxpluginmodel',
            old_name='bild',
            new_name='bildasd',
        ),
    ]
