# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('cms_plugins', '0003_auto_20191013_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParallaxPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_parallaxpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('bild', models.ImageField(upload_to='parallax-background-images/')),
                ('text', models.CharField(default='Text der Überschrift', max_length=128)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='parralaxpluginmodel',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='ParralaxPluginModel',
        ),
    ]
