# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('cms_plugins', '0004_auto_20191013_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitParagraphPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_splitparagraphpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='headlinepluginmodel',
            name='text',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='parallaxpluginmodel',
            name='text',
            field=models.CharField(max_length=128),
        ),
    ]
