# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0005_auto_20191013_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallaxpluginmodel',
            name='text',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
