# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0006_auto_20191013_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallaxpluginmodel',
            name='text',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
