# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0007_auto_20191013_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_mappluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('karte_bild', models.ImageField(upload_to='map-images/')),
                ('legende_bild', models.ImageField(upload_to='map-images/')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
