# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0009_auto_20200513_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappluginmodel',
            name='legende_bild',
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_1_bild',
            field=models.FileField(default='', upload_to='map-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_1_text',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_2_bild',
            field=models.FileField(default='asd', upload_to='map-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_2_text',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_3_bild',
            field=models.FileField(default='asd', upload_to='map-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='legende_3_text',
            field=models.CharField(default='asd', max_length=128),
            preserve_default=False,
        ),
    ]
