# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0011_listandimagepluginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappluginmodel',
            old_name='karte_bild',
            new_name='karte_bild_1',
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='karte_bild_2',
            field=models.FileField(default=None, upload_to='map-images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mappluginmodel',
            name='karte_bild_3',
            field=models.FileField(default=None, upload_to='map-images/'),
            preserve_default=False,
        ),
    ]
