# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0012_auto_20200612_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappluginmodel',
            old_name='karte_bild_1',
            new_name='karte_1_bild',
        ),
        migrations.RenameField(
            model_name='mappluginmodel',
            old_name='karte_bild_2',
            new_name='karte_2_bild',
        ),
        migrations.RenameField(
            model_name='mappluginmodel',
            old_name='karte_bild_3',
            new_name='karte_3_bild',
        ),
    ]
