# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0013_auto_20200612_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlinepluginmodel',
            name='link',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
